### ISSUE TITLE
can you help me?

### ISSUE THREAD

**Issue by longmalongma** [liuxinhai/Point2Sequence#2]
Can you help me?when I try to train your models I meet this problem.
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'FarthestPointSample' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: layer1/FarthestPointSample = FarthestPointSample[npoint=384, _device="/device:GPU:0"](Placeholder)]]

**Comment by liuxinhai** [comment]
> Can you help me?when I try to train your models I meet this problem.
> InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'FarthestPointSample' with these attrs. Registered devices: [CPU], Registered kernels:
> device='GPU'
> 
> ```
>  [[Node: layer1/FarthestPointSample = FarthestPointSample[npoint=384, _device="/device:GPU:0"](Placeholder)]]
> ```

**Comment by liuxinhai** [comment]
> Can you help me?when I try to train your models I meet this problem.
> InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'FarthestPointSample' with these attrs. Registered devices: [CPU], Registered kernels:
> device='GPU'
> 
> ```
>  [[Node: layer1/FarthestPointSample = FarthestPointSample[npoint=384, _device="/device:GPU:0"](Placeholder)]]
> ```

**Comment by liuxinhai** [comment]
Please check the following two points:
1. Whether to correctly compile and generate  tf_sampling_so.so as described in PointNet++?
2. 'FarthestPointSample' function only support GPU.

**Comment by longmalongma** [comment]
> Please check the following two points:
> 
>     1. Whether to correctly compile and generate  tf_sampling_so.so as described in PointNet++?
> 
>     2. 'FarthestPointSample' function only support GPU.

Think you for your reply,can you send me three have compiled files in tf_ops folder?

**Comment by longmalongma** [comment]
> > Please check the following two points:
> > ```
> > 1. Whether to correctly compile and generate  tf_sampling_so.so as described in PointNet++?
> > 
> > 2. 'FarthestPointSample' function only support GPU.
> > ```
> 
> Think you for your reply,can you send me three have compiled files in tf_ops folder?

my email is that:1442342449@qq.com

**Comment by Luznss** [comment]
> Please check the following two points:
> 
> 1. Whether to correctly compile and generate  tf_sampling_so.so as described in PointNet++?
> 2. 'FarthestPointSample' function only support GPU.

I aosl

> Please check the following two points:
> 
> 1. Whether to correctly compile and generate  tf_sampling_so.so as described in PointNet++?
> 2. 'FarthestPointSample' function only support GPU.

Could you help me? I also meet same this problem. but i have  running pointnet++ normal

**Comment by Luznss** [comment]
Could you help me? I also meet same this problem. but i have running pointnet++ normal
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'FarthestPointSample' with these attrs. Registered devices: [CPU], Registered kernels:
device='GPU'

**Comment by liuxinhai** [comment]
From the error message， I still think that you may build the network on the CPU device. Please check the part of network building. Moreover, you can download my compiled .so files at
https://drive.google.com/drive/folders/1KBbRLSg4UXZetY6VCP1zsnSIp6oHuJK3?usp=sharing
Best wishes!

**Comment by Luznss** [comment]
> From the error message， I still think that you may build the network on the CPU device. Please check the part of network building. Moreover, you can download my compiled .so files at
> https://drive.google.com/drive/folders/1KBbRLSg4UXZetY6VCP1zsnSIp6oHuJK3?usp=sharing
> Best wishes!

Think you for your help！

**Comment by longmalongma** [comment]
> > From the error message， I still think that you may build the network on the CPU device. Please check the part of network building. Moreover, you can download my compiled .so files at
> > https://drive.google.com/drive/folders/1KBbRLSg4UXZetY6VCP1zsnSIp6oHuJK3?usp=sharing
> > Best wishes!
> 
> Think you for your help！

Have you successfully run this code on your computer?I can't run it.
